Feature/external adapter part 1
thearthurchen/TogetherWeRun pull request #8
Opened 2021-04-06 04:38 UTC by zackwoo808

2021-04-06 04:42 UTC, zackwoo808 commented on StravaExternalAdapter/index.js
> +// #region wrapper functions
haven't exposed these yet

2021-04-06 04:46 UTC, zackwoo808 commented on StravaExternalAdapter/app.js
> +        timestamp: Date.now() // TODO
not sure what type of timestamp we want?

2021-04-07 16:36 UTC, tannervelten requested changes
Adding this in case you wanna take a look, but we can review later. Think I dropped the ball a bit on explaining where to add your code

2021-04-07 16:36 UTC, tannervelten commented on StravaExternalAdapter/app.js
> -app.post('/', (req, res) => {
We need this

2021-04-07 16:36 UTC, tannervelten commented on StravaExternalAdapter/app.js
> +app.post('/get-athlete-activity', (req, res) => {
Don't need this endpoint, business logic can go in https://github.com/thearthurchen/TogetherWeRun/blob/main/StravaExternalAdapter/strava.js#L4

2021-04-07 16:36 UTC, tannervelten commented on StravaExternalAdapter/app.js
> +app.post('/create-new-user', (req, res) => {
Good

2021-04-07 16:36 UTC, tannervelten commented on StravaExternalAdapter/index.js
> -const { Requester, Validator } = require('@chainlink/external-adapter')
This file handles the req/res for EA -- you shouldn't need to make changes here

2021-04-08 06:00 UTC, closed without merging